Comeback practice
IrinaMilekhina/basic_practicing pull request #3
Opened 2024-08-14 16:07 UTC by thetribalme

First 5 tasks

2024-08-15 20:16 UTC, IrinaMilekhina requested changes
Зачем тут папки  .idea и lala?

2024-08-16 12:33 UTC, darkeugene requested changes

2024-08-16 12:33 UTC, darkeugene commented on .idea/.gitignore
Давайте сюда добавим .idea также, чтобы не тянуть всё лишнее в репу, что создалось IDE для себя любимого :)

2024-08-16 12:33 UTC, darkeugene commented on comeback/1.py
> +pattern = re.compile(r"^\d{4}\.[0,1]\d\.[0-3]\d$")
давайте однообразие соблюдём и будем преимущественно использовать одинарные кавычки для строк.
Исключение: если в тексте есть апостроф, то там без двойных никак

2024-08-16 12:33 UTC, darkeugene commented on comeback/1.py
> +pattern = re.compile(r"^\d{4}\.[0,1]\d\.[0-3]\d$")
А если я пришлю дату '2024-18-39'? кажется, что обработает такую дату :)

2024-08-16 12:33 UTC, darkeugene commented on comeback/4.py
> +        initial_list[initial_list.index(element)] = initial_list[-1]
Тут на подумать: а какая сложность получится?
Подсказка: почитать про `enumerate`

2024-08-16 12:52 UTC, IrinaMilekhina commented on comeback/4.py
> +        initial_list[initial_list.index(element)] = initial_list[-1]
Мы еще не проходили сложность
Но почитать полезно =)

2024-09-11 15:04 UTC, darkeugene commented on comeback/1.py
> +    day = user_input.split('.')[2]
Кажется, что тут излишнее сплитование происходит. Каждый раз, когда мы выполняем сплит, мы затрачиваем наши вычислительные ресурсы и делать 3 раза одно и тоже действие видится не очень выгодным с точки зрения затрат вычислительных ресурсов.
Может быть стоит рассмотреть вариант того, чтобы не делать сплит 3 раза?

2024-10-30 15:28 UTC, thetribalme commented on comeback/1.py
> +    day = user_input.split('.')[2]
Властью данной мне Ирой, я вливаю ветку)
Ира: обобрено!

2024-10-30 15:31 UTC, merged